ROM	EQU	$C000	DEFINO DONDE EMPIEZA LA ROM
RAM	EQU	$0000	DEFINO DONDE EMPIEZA LA ROM
RESET 	EQU	$FFFE

	ORG 	RAM	DEFINO VALORES DE LAS VARIABLES
OP1	RMB	4
OP2	RMB	4
RES	RMB 	5				
						
	ORG 	ROM
INICIO		
	CLR	RES	LIMPIA LA POSICION DE MEMORIA DE RES (DONDE COMIENZA)
	CLC		PONE EL CARRY EN 0					
	LDAB	#4	CARGO EL REGISTRO B CON EL NUMERO DE LA POSICION DE MEMORIA 4, SI NO PONGO NUMERAL CARGO EL CONTENIDO	
	LDX	#OP1+3	CARGA EL REGISTRO INDICE X CON LA POSICION DE MEMORIA OP1+3
LOOP 	
	LDAA	0,X	CARGA EL CONTENIDO DE LA POSICION DE MEMORIA 0, X (QUE ES OP1+3)
	ADCA	4,X	SUMA EL ACUM A CON EL CONTENIDO DE LA POS DE X (QUE ES OP1+3) + 4 Y SI TIENE CARRY ANTERIOR SE LO SUMA
	STAA	9,X 	STOREA LA POSICION DE MEMORIA DE X (QUE ES OP1+3) + 9 Y GUARDA ALLI EL VALOR QUE TIENE ALMACENADO ACUM A
	DEX		DECREMENTA LA POSICION DE MEMORIA DEL REGISTRO X --> = (OP1+3)-1
	DECB		DECREMENTA EL NUMERO DE LA POSICION DE MEMORIA DEL REGISTRO B --> = (4)-1
	BNE	LOOP	SALTA SI B NO ES 0, COMPARA B CON 0

	BCC	SIGUE	SI EL CARRY ES 0 SALTA A SIGUE, SINO SUMA 1
	INC 	RES
SIGUE			

FIN	BRA	FIN
	ORG 	RESET
	DW 	INICIO



		