ROM		EQU		$C000
RAM		EQU		$0000
RESET		EQU		$FFFE

		ORG 		RAM
AUX		RMB 		1
OP1		RMB		1
OP2		RMB		1		
		
						;ACA DEFINO LOS OPERANDOS
		ORG 		ROM
INICIO						;ACA DEFINO QUE COINCA QUIERO HACER
		LDAA		AUX          ;LOAD ACUMULADOR A 
		ADDA      	#15		;LE SUMO 15 (DECIMAL) AL REGISTRO A
						

FIN		BRA		FIN
		ORG		RESET
		DW		INICIO




		