ROM	EQU	$C000	DEFINO DONDE EMPIEZA LA ROM
RAM	EQU	$0000	DEFINO DONDE EMPIEZA LA ROM
RESET 	EQU	$FFFE

	ORG 	RAM	DEFINO VALORES DE LAS VARIABLES
OP1	RMB	2
OP2	RMB	2
RES	RMB 	3		
AUX     RMB	1		
						
	ORG 	ROM
INICIO		
	CLR	AUX					
	LDAA	OP1+1    	 	
	LDAB	OP2+1   
	ABA		
	STAA	RES+2	
	BCC	SIGUE	
	INC 	AUX	LE SUMO 1 A AUX SI ES QUE HAY CARRY EN LA PRIMERA PARTE
SIGUE			
	CLR	RES
	LDAA	OP1    	 	
	LDAB	OP2   
	ABA			
	BCC	SIGUE2	
	INC 	RES	LE SUMO 1 A RES SI ES QUE HAY CARRY ENTRE LA POS OP1 Y OP2
SIGUE2	
	LDAB	AUX	CARGO B CON AUX	
	ABA		EN EL ACUMULADOR A TENIA ACUM A=OP1 + ACUM B=OP2 Y ENTONCES LE SUMO UNO SI TENIA CARRY ANTES
	STAA	RES+1	GUARDO EN RES+1 LA SUMA DE OP1+OP2 + POSIBLE CARRY (PUEDE ESTAR EN 0 O EN 1)
	BCC	SIGUE3	SI LO ANTERIOR ME DIO 0 DE CARRY SALTO Y TERMINO
	INC 	RES	ME PUEDE LLEGAR A DAR CARRY CUANDO SUMO EL CARRY DE LA POS RES+1 CON AUX
SIGUE3

FIN	BRA	FIN
	ORG 	RESET
	DW 	INICIO



		