ROM	EQU	$C000	DEFINO DONDE EMPIEZA LA ROM
RAM	EQU	$0000	DEFINO DONDE EMPIEZA LA ROM
RESET 	EQU	$FFFE

	ORG 	RAM	DEFINO VALORES DE LAS VARIABLES
OP1	RMB	1
OP2	RMB	1
RES	RMB 	2		
		
						
	ORG 	ROM
INICIO						
	CLR	RES	LIMPIO EL RESULTADO DEL CARRY PORQUE COMO NO LO STOREO CAPAZ TIENE OTRO VALOR					
	LDAA	OP1     GUARDA EN OP1 LO QUE HAY EN MEMORIA 	 	
	LDAB	OP2    	GUARDA EN OP2 LO QUE HAY EN MEMORIA 
	ABA		SUMA A+B
	STAA	RES+1	STOREA EN LA POS DE RES+1 (PARTE MENOS SIGNIFICATIVA)
	BCC	SIGUE	SALTA SI CARRY 0
	INC 	RES	SI CARRY ES 1 LO SUMA EN LA PARTE MAS SIGNIFICATIVA DE RES

SIGUE				

FIN	BRA	FIN
	ORG 	RESET
	DW 	INICIO



		