ROM	EQU	$C000	DEFINO DONDE EMPIEZA LA ROM
RAM	EQU	$0000	DEFINO DONDE EMPIEZA LA ROM
RESET 	EQU	$FFFE

	ORG 	RAM	DEFINO VALORES DE LAS VARIABLES
OP1	RMB	4
OP2	RMB	4
RES	RMB 	5				
						
	ORG 	ROM
INICIO		
	CLR	RES
	CLC		PONE EL CARRY EN 0					
	LDAA	OP1+3	CARGA EL ACUMULADOR A	 	
	ADCA	OP2+3 	LE SUMA A AC A EL LO QUE HAYA EN OP2 Y SI TIENE CARRY TAMBIEN SE LO SUMA (EN ESTE CASO ES 0 PORQUE ES LA PRIMERA CUENTA))
	STAA	RES+4	STOREA EL ACUMULADOR A

	LDAA	OP1+2    	 	
	ADCA	OP2+2   
	STAA	RES+3	

	LDAA	OP1+1    	 	
	ADCA	OP2+1   
	STAA	RES+2	

	LDAA	OP1    	 	
	ADCA	OP2   
	STAA	RES+1

	BCC	SIGUE	
	INC 	RES
SIGUE			

FIN	BRA	FIN
	ORG 	RESET
	DW 	INICIO



		