ROM        	EQU     $C000
RAM        	EQU     $0000

TAM		EQU     128
	
        ORG     RAM

VECTOR  	RMB     TAM

        ORG     ROM

        LDS     #$00FF
        LDX     #VECTOR
        CLRA
        CLRB

MAIN
    	JSR    	POSMIN
FIN	BRA     FIN

POSMIN
	;PSHA
	;PSHB
	;PSHY

    	LDD    	0,X
	BEQ    	LEE0       	SALTA SI ES 0
	LDY     0,X		PRIMER VALOR DEL VECTOR, LO GUARDO COMO VALOR MINIMO
	
LOOP
	INX
   	INX
	LDD    	0,X		CARGO AL VECTOR CON EL VALOR SIGUIENTE
	BEQ    	LEE0       	SALTA SI ES 0
   	CPY    	0,X		COMPARA LO QUE HAY EN Y CON LO QUE HAY EN LA MEMORIA EN LA POSICION DEL VECTOR X ACTUAL
	BLT     SALTO           SI LA RESTA DA NEGATIVO XOR OVERFLOX (X > Y), 'Y' SIGUE SIENDO MENOR-->NO LO GUARDO
   	LDY     0,X             SI LA RESTA NO DIO NEGATIVO XOR OVERFLOX (X > Y), ENTONCES LO GUARDO COMO MENOR EN 'Y'
SALTO 
 	BRA     LOOP
	;PULY
	;PULB
	;PULA

LEE0
NOERA
	DEX
	DEX
	CPY	0,X		COMPARA LO QUE HAY EN 'X' CON EL VALOR MINIMO QUE OBTUVE QUE LO HABIA GUARDADO EN 'Y'
	BEQ	POSICION	ME DICE SI LA RESTA ENTRE LOS NUMEROS DIO 0
	BRA     NOERA
	
POSICION		
    	RTS

    ORG     VECTOR

	DW    2,1,3,-3,-2,0,-23450,-30000,10,0,-23450,0,30080,30200,30000
	DW    1,30000,15450,-30600,-30080,30200,30000
	DW    31000,30000,12450,30600,30080,30200