ROM        	EQU     $C000
RAM        	EQU     $0000

TAM		EQU   	64
TAMB		EQU	1
	
        ORG     RAM

VECTOR  RMB	TAM
VTRCOMP RMB	TAM

        ORG     ROM

      	LDS  	#$00FF
      	LDX  	#VECTOR
	LDY	#VTRCOMP
      	CLRA
	LDAB	#TAMB

MAIN
    	JSR    	COMP2BEB
FIN	BRA     FIN

COMP2BEB
LOOP	
	INX
	INY
	DECB				
	BNE	LOOP	
	BEQ	COMIENZA

COMIENZA
	LDAB	#TAMB

NOTERMINO

	CMPB	#TAMB
	BHS	ULTBYTE	SALTA SI ES MAYOR O IGUAL, OSEA SALTA SI ESTA PROBANDO EL ULTIMO BYTE(ES LA PRIMERA ITERACION)
    	LDAA  	0,X
     	COMA			CALCULA EL COMPLEMENTO A LA BASE MENOS UNO $FF - EL VALOR DE A
	STAA	0,Y
	DEY
	DEX
	INCB	
	DECB
	BEQ	TERMINO

ULTBYTE
	LDAA  	0,X
     	COMA			CALCULA EL COMPLEMENTO A LA BASE MENOS UNO $FF - EL VALOR DE A
      	ADDA  	#1           LE SUMO UNO PARA HACER EL COMPLEMENTO
	STAA	0,Y
	DEY
	DEX
	DECB
	BRA	NOTERMINO

TERMINO
    	RTS

    ORG     VECTOR

	DW	1628