ROM		EQU	$C000
RAM		EQU	$0000	
			
TAM		EQU	128

		ORG 	RAM
	
VECTOR       RMB    TAM

		ORG 	ROM
		
		LDS	#$00FF
		LDX   	#0
		LDY	#VECTOR
		CLRA
		CLRB
		
MAIN
	JSR	PROMPOS
FIN	BRA	FIN

PROMPOS			
				;FUNCIONA PARA TODOS ESTOS CASOS
				;0000 0000
				;0000 0001
				;1000 0000
SALTO
	LDAB 0,Y
	BEQ  	LEE0		SALTA SI ES 0
	BLT	ESMENOR		SALTA SI ES MENOR QUE 0
	ABX 			SUMA B A REGISTRO X (X ES LA SUMA TOTAL)
	INCA			CONTADOR DE NUMERO POSITIVOS (ES POR LO QUE TENGO QUE DIVIDIR X)			
	
ESMENOR
	INY
	BRA	SALTO		SALTA SIEMPRE
LEE0
	TSTA			SE FIJA SI A ES 0
	BEQ	NOPOS		SI A NUNCA LEYO POSITIVOS NO PUEDE DIVIDIR POR 0 ENTONCES TERMINA
	TAB			TRANSFIERE DE A A B
	CLRA			LIMPIA A (HACEINDO ESTA LINEA Y LA ANTERIOR DEJE B EN LA PARTE BAJA DE D PARA USARLO COMO DIVISOR)
	XGDX			CAMBIA X POR D Y D POR X (ENTONCES AHORA EL DIVISOR ESTA EN X)
	IDIV			DIVIDE D CON X---->> D/X, EL RTO LO GUARDA EN X Y EL RESTO EN D
NOPOS
	RTS
	

	ORG 	VECTOR

	DB    -11,-120,-40,0,30,20,0

		