ROM        	EQU     $C000
RAM        	EQU     $B600

TAM		EQU   	32
TAMCONT		EQU	2	

	      	ORG  	RAM

VECTORX  	RMB   	TAM
CONTADOR	RMB	TAMCONT

        	ORG     ROM

      		;LDS   	#$00FF
      		LDX   	#VECTORX
		CLR	CONTADOR
		CLR	CONTADOR+1
      		CLRA
      		CLRB

MAIN

LOOP
	LDAA 	0,X	CARGO EL ACUMULADOR A CON LA PRIMERA POSICION DEL VECTOR Y SIEMPRE APUNTA A X YA QUE LO VOY INCREMENTANDO
	BEQ	LEE0	SI LEE EL VALOR 00 ES NULL ENTONCES TERMINA	

	CMPA	#'9	COMPARE EL ACUMULADOR A CON Z EN ASCII
	BHI	NOERA	SI ES MAYOR QUE Z NO VA A ESTAR COMPRENDIDO ENTRE 1 Y 9, SALTA SI ES MAYOR
	CMPA	#'1	COMPARE EL ACUMULADOR A CON 0 EN ASCII
	BHS	ESNUM	SALTA SI ES MAYOR O IGUAL QUE 0
	INX
	BRA	LOOP	

ESNUM	

	INC	CONTADOR+1
	INX
	BRA 	LOOP

NOERA	
	INX
	BRA 	LOOP
LEE0
	LDY	CONTADOR
FIN	BRA     FIN


    ORG     VECTORX

	DB	'R,'I,'b,'e,'r,'s,'o,'s','d','e,'l,'a,'B
	DB	'1,'2,0